// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-f7gpuuboCmq8LuZokf6_x7izUWz-A70',
    appId: '1:283588132639:web:ba94e0d605044e014afa2a',
    messagingSenderId: '283588132639',
    projectId: 'proyek-sipilah',
    authDomain: 'proyek-sipilah.firebaseapp.com',
    databaseURL: 'https://proyek-sipilah-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'proyek-sipilah.firebasestorage.app',
    measurementId: 'G-3NBXDZFGZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP52vM2DXu2_TdOGuGWKS1Q2ELysD2uZg',
    appId: '1:283588132639:android:150963b64755048c4afa2a',
    messagingSenderId: '283588132639',
    projectId: 'proyek-sipilah',
    databaseURL: 'https://proyek-sipilah-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'proyek-sipilah.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcBBxaS-qwmb-k786f9Su4wrcE1IQDMJ4',
    appId: '1:283588132639:ios:abf0b6a08e66c4254afa2a',
    messagingSenderId: '283588132639',
    projectId: 'proyek-sipilah',
    databaseURL: 'https://proyek-sipilah-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'proyek-sipilah.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcBBxaS-qwmb-k786f9Su4wrcE1IQDMJ4',
    appId: '1:283588132639:ios:abf0b6a08e66c4254afa2a',
    messagingSenderId: '283588132639',
    projectId: 'proyek-sipilah',
    databaseURL: 'https://proyek-sipilah-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'proyek-sipilah.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-f7gpuuboCmq8LuZokf6_x7izUWz-A70',
    appId: '1:283588132639:web:48ad69a1deb4b1684afa2a',
    messagingSenderId: '283588132639',
    projectId: 'proyek-sipilah',
    authDomain: 'proyek-sipilah.firebaseapp.com',
    databaseURL: 'https://proyek-sipilah-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'proyek-sipilah.firebasestorage.app',
    measurementId: 'G-30YJ20DVFE',
  );

}